#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www 
#points to your load-balancer IP

if [ "$#" -eq 1 ]
then
	for items in "www" "lb-01" "web-01" "web-02"
	do
		dig "$items"".""$1" | grep -A1 'ANSWER SECTION:' | awk -v sub_dom="$items" ' NR==2 {print "The subdomain " sub_dom " is a " $4 " record and points to " $5}'
 
	done
else
	dig "$2"".""$1" | grep -A1 'ANSWER SECTION:' | awk -v sub_dom="$2" ' NR==2 {print "The subdomain " sub_dom " is a " $4 " record and points to " $5}'
 
fi
