#!/usr/bin/env bash
#configure web-02 to be identical to web-01
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
