#!/usr/bin/env bash
#that loops from 1 to 10 and bad luck, good luck.
c=1
while [ $c -le 10 ]
do
	if [ $c = 4 ]
	then
		echo "bad luck"
	elif [ $c = 8 ]
	then	
		echo "goog luck"
	else 
		echo "Holberton School"
	fi
	c=$((c = c + 1))
done
