#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

c=0
while [ $c -le 12 ]
do
	echo "Hour: $c"
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((c++))
done
